# Generated by Django 4.0.5 on 2022-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=30)),
                ('integrantes', models.IntegerField()),
                ('emailclub', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=30)),
                ('integrantes', models.IntegerField()),
                ('creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rugby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=30)),
                ('integrantes', models.IntegerField()),
                ('creacion', models.DateField()),
            ],
        ),
    ]
